# Definitions and utilities for unfccc reporting
import re

# categories derived from https://github.com/WattTime/climate-trace-analysis-util/blob/main/inventories/unfccc_annex1.csv
UNFCCC_CATEGORIES = ["1.  Energy",
"1.A.1  Energy Industries",
"1.A.1.a  Public Electricity and Heat Production",
"1.A.1.a.i  Electricity Generation",
"1.A.1.a.ii  Combined Heat and Power Generation",
"1.A.1.a.iii  Heat Plants",
"1.A.1.a.iv  Other",
"1.A.1.b  Petroleum Refining",
"1.A.1.c  Manufacture of Solid Fuels and Other Energy Industries",
"1.A.1.c.i  Manufacture of Solid Fuels",
"1.A.1.c.ii  Oil and Gas Extraction",
"1.A.1.c.iii  Other Energy Industries",
"1.A.1.c.iv  Other",
"1.A.2  Manufacturing Industries and Construction",
"1.A.2.a  Iron and Steel",
"1.A.2.b  Non-Ferrous Metals",
"1.A.2.c  Chemicals",
"1.A.2.d  Pulp, Paper and Print",
"1.A.2.e  Food Processing, Beverages and Tobacco",
"1.A.2.f  Non-metallic Minerals",
"1.A.2.g  Other",
"1.A.2.g.i  Manufacturing of Machinery",
"1.A.2.g.ii  Manufacturing of Transport Equipment",
"1.A.2.g.iii  Mining (Excluding Fuels) and Quarrying",
"1.A.2.g.iv  Wood and Wood Products",
"1.A.2.g.v  Construction",
"1.A.2.g.vi  Textile and Leather",
"1.A.2.g.vii  Off-road Vehicles and Other Machinery",
"1.A.2.g.viii  Other",
"1.A.3  Transport",
"1.A.3.a  Domestic Aviation",
"1.A.3.b  Road Transportation",
"1.A.3.b.i  Cars",
"1.A.3.b.ii  Light Duty Trucks",
"1.A.3.b.iii  Heavy Duty Trucks and Buses",
"1.A.3.b.iv  Motorcycles",
"1.A.3.b.v  Other",
"1.A.3.c  Railways",
"1.A.3.d  Domestic Navigation",
"1.A.3.e  Other Transportation",
"1.A.3.e.i  Pipeline Transport",
"1.A.3.e.ii  Other",
"1.A.4  Other Sectors",
"1.A.4.a  Commercial/Institutional",
"1.A.4.a.i  Stationary Combustion",
"1.A.4.a.ii  Off-road Vehicles and Other Machinery",
"1.A.4.a.iii  Other",
"1.A.4.b  Residential",
"1.A.4.b.i  Stationary Combustion",
"1.A.4.b.ii  Off-road Vehicles and Other Machinery",
"1.A.4.b.iii  Other",
"1.A.4.c  Agriculture/Forestry/Fishing",
"1.A.4.c.i  Stationary",
"1.A.4.c.ii  Off-road Vehicles and Other Machinery",
"1.A.4.c.iii  Fishing",
"1.A.5  Other (Not specified elsewhere)",
"1.A.5.a  Stationary",
"1.A.5.b  Mobile",
"1.AA  Fuel Combustion - Sectoral approach",
"1.AB  Fuel Combustion - Reference Approach",
"1.AD  Feedstocks, Reductants and Other Non-energy Use of Fuels",
"1.B  Fugitive Emissions from Fuels",
"1.B.1  Solid Fuels",
"1.B.1.a  Coal Mining and Handling",
"1.B.1.a.i  Underground Mines",
"1.B.1.a.i.1  Mining Activities",
"1.B.1.a.i.2  Post-Mining Activities",
"1.B.1.a.i.3  Abandoned Underground Mines",
"1.B.1.a.ii  Surface Mines",
"1.B.1.a.ii.1  Mining Activities",
"1.B.1.a.ii.2  Post-Mining Activities",
"1.B.1.b  Solid Fuel Transformation",
"1.B.1.c  Other",
"1.B.2  Oil and Natural Gas and Other Emissions from Energy Production",
"1.B.2.a  Oil",
"1.B.2.a.i  Exploration",
"1.B.2.a.ii  Production",
"1.B.2.a.iii  Transport",
"1.B.2.a.iv  Refining / Storage",
"1.B.2.a.v  Distribution of Oil Products",
"1.B.2.a.vi  Other",
"1.B.2.b  Natural Gas",
"1.B.2.b.i  Exploration",
"1.B.2.b.ii  Production",
"1.B.2.b.iii  Processing",
"1.B.2.b.iv  Transmission and Storage",
"1.B.2.b.v  Distribution",
"1.B.2.b.vi  Other",
"1.B.2.c  Venting and Flaring",
"1.B.2.c.i  Venting",
"1.B.2.c.i.1  Oil",
"1.B.2.c.i.2  Gas",
"1.B.2.c.i.3  Combined",
"1.B.2.c.ii  Flaring",
"1.B.2.c.ii.1  Oil",
"1.B.2.c.ii.2  Gas",
"1.B.2.c.ii.3  Combined",
"1.B.2.d  Other",
"1.C  CO₂ Transport and Storage",
"1.C.1  Transport of CO₂",
"1.C.1.a  Pipelines",
"1.C.1.b  Ships",
"1.C.1.c  Other",
"1.C.2  Injection and Storage",
"1.C.2.a  Injection",
"1.C.2.b  Storage",
"1.C.3  Other",
"2.  Industrial Processes and Product Use",
"2.A  Mineral Industry",
"2.A.1  Cement Production",
"2.A.2  Lime Production",
"2.A.3  Glass production",
"2.A.4  Other Process Uses of Carbonates",
"2.A.4.a  Ceramics",
"2.A.4.b  Other Uses of Soda Ash",
"2.A.4.c  Non-metallurgical Magnesium Production",
"2.A.4.d  Other",
"2.B  Chemical Industry",
"2.B.1  Ammonia Production",
"2.B.10  Other",
"2.B.2  Nitric Acid Production",
"2.B.3  Adipic Acid Production",
"2.B.4  Caprolactam, Glyoxal and Glyoxylic Acid Production",
"2.B.4.a  Caprolactam",
"2.B.4.b  Glyoxal",
"2.B.4.c  Glyoxylic Acid",
"2.B.5  Carbide Production",
"2.B.5.a  Silicon Carbide",
"2.B.5.b  Calcium Carbide",
"2.B.6  Titanium Dioxide Production",
"2.B.7  Soda Ash Production",
"2.B.8  Petrochemical and Carbon Black Production",
"2.B.8.a  Methanol",
"2.B.8.b  Ethylene",
"2.B.8.c  Ethylene Dichloride and Vinyl Chloride Monomer",
"2.B.8.d  Ethylene Oxide",
"2.B.8.e  Acrylonitrile",
"2.B.8.f  Carbon Black",
"2.B.8.g  Other",
"2.B.8.g.i  Styrene",
"2.B.8.g.ii  Other",
"2.B.9  Fluorochemical Production",
"2.B.9.a  By-Product Emissions",
"2.B.9.a.i  Production of HCFC-22",
"2.B.9.a.ii  Other",
"2.B.9.b  Fugitive Emissions",
"2.B.9.b.i  Production of HFC-134a",
"2.B.9.b.ii  Production of SF₆",
"2.B.9.b.iii  Other",
"2.C  Metal Industry",
"2.C.1  Iron and Steel Production",
"2.C.1.a  Steel",
"2.C.1.b  Pig Iron",
"2.C.1.c  Direct Reduced Iron",
"2.C.1.d  Sinter",
"2.C.1.e  Pellet",
"2.C.1.f  Other",
"2.C.2  Ferroalloys Production",
"2.C.3  Aluminium Production",
"2.C.3.a  CO₂ Emissions",
"2.C.3.b  By-Product Emissions",
"2.C.3.c  F-gases Used in Foundries",
"2.C.4  Magnesium Production",
"2.C.5  Lead Production",
"2.C.6  Zinc Production",
"2.C.7  Other",
"2.D  Non-energy Products from Fuels and Solvent Use",
"2.D.1  Lubricant Use",
"2.D.2  Paraffin Wax Use",
"2.D.3  Other",
"2.D.3.a  Solvent Use",
"2.D.3.b  Road Paving with Asphalt",
"2.D.3.c  Asphalt Roofing",
"2.D.3.d  Other",
"2.E  Electronics Industry",
"2.E.1  Integrated Circuit or Semiconductor",
"2.E.2  TFT Flat Panel Display",
"2.E.3  Photovoltaics",
"2.E.4  Heat Transfer Fluid",
"2.E.5  Other",
"2.F  Product Uses as Substitutes for ODS",
"2.F.1  Refrigeration and Air-conditioning",
"2.F.1.a  Commercial Refrigeration",
"2.F.1.b  Domestic Refrigeration",
"2.F.1.c  Industrial Refrigeration",
"2.F.1.d  Transport Refrigeration",
"2.F.1.e  Mobile Air-conditioning",
"2.F.1.f  Stationary Air-conditioning",
"2.F.2  Foam Blowing Agents",
"2.F.2.a  Closed Cells",
"2.F.2.b  Open Cells",
"2.F.3  Fire Protection",
"2.F.4  Aerosols",
"2.F.4.a  Metered Dose Inhalers",
"2.F.4.b  Other",
"2.F.5  Solvents",
"2.F.6  Other Applications",
"2.F.6.a  Emissive",
"2.F.6.b  Contained",
"2.G  Other Product Manufacture and Use",
"2.G.1  Electrical Equipment",
"2.G.2  SF₆ and PFCs from Other Product Use",
"2.G.2.a  Military Applications",
"2.G.2.b  Accelerators",
"2.G.2.c  Soundproof Windows",
"2.G.2.d  Adiabatic Properties: Shoes and Tyres",
"2.G.2.e  Other",
"2.G.3  N₂O from Product Uses",
"2.G.3.a  Medical Applications",
"2.G.3.b  Other",
"2.G.3.b.i  Propellant for Pressure and Aerosol Products",
"2.G.3.b.ii  Other",
"2.G.4  Other",
"2.H  Other",
"2.H.1  Pulp and Paper",
"2.H.2  Food and Beverages Industry",
"2.H.3  Other",
"3.  Agriculture",
"3.A  Enteric Fermentation",
"3.B  Manure Management",
"3.C  Rice Cultivation",
"3.C.1  Irrigated",
"3.C.1.a  Continuously Flooded",
"3.C.1.b  Intermittently Flooded",
"3.C.1.b.i  Single Aeration",
"3.C.1.b.ii  Multiple Aeration",
"3.C.2  Rainfed",
"3.C.2.a  Flood Prone",
"3.C.2.b  Drought Prone",
"3.C.3  Deep Water",
"3.C.3.a  Water Depth 50-100 cm",
"3.C.3.b  Water Depth > 100 cm",
"3.C.4  Other",
"3.D  Agricultural Soils",
"3.D.1  Direct N₂O Emissions From Managed Soils",
"3.D.1.a  Inorganic N Fertilizers",
"3.D.1.b  Organic N Fertilizers",
"3.D.1.b.i  Animal Manure Applied to Soils",
"3.D.1.b.ii  Sewage Sludge Applied to Soils",
"3.D.1.b.iii  Other Organic Fertilizers Applied to Soils",
"3.D.1.c  Urine and Dung Deposited by Grazing Animals",
"3.D.1.d  Crop Residues",
"3.D.1.e  Mineralization/Immobilization Associated with Loss/Gain of Soil Organic Matter",
"3.D.1.f  Cultivation of Organic Soils",
"3.D.1.g  Other",
"3.D.2  Indirect N₂O Emissions From Managed Soils",
"3.D.2.a  Atmospheric Deposition",
"3.D.2.b  Nitrogen Leaching and Run-off",
"3.E  Prescribed Burning of Savannas",
"3.E.1  Forest Land",
"3.E.2  Grassland",
"3.F  Field Burning of Agricultural Residues",
"3.F.1  Cereals",
"3.F.1.a  Wheat",
"3.F.1.b  Barley",
"3.F.1.c  Maize",
"3.F.1.d  Other",
"3.F.2  Pulses",
"3.F.3  Tubers and Roots",
"3.F.4  Sugar Cane",
"3.F.5  Other",
"3.G  Liming",
"3.G.1  Limestone CaCO₃",
"3.G.2  Dolomite CaMg(CO₃)₂",
"3.H  Urea Application",
"3.I  Other Carbon-containing Fertilizers",
"3.J  Other",
"4.  Land Use, Land-Use Change and Forestry",
"4.A  Forest Land",
"4.A.1  Forest Land Remaining Forest Land",
"4.A.2  Land Converted to Forest Land",
"4.A.2.a  Cropland Converted to Forest Land",
"4.A.2.b  Grassland Converted to Forest Land",
"4.A.2.c  Wetlands Converted to Forest Land",
"4.A.2.d  Settlements Converted to Forest Land",
"4.A.2.e  Other Land Converted to Forest Land",
"4.B  Cropland",
"4.B.1  Cropland Remaining Cropland",
"4.B.2  Land Converted to Cropland",
"4.B.2.a  Forest Land Converted to Cropland",
"4.B.2.b  Grassland Converted to Cropland",
"4.B.2.c  Wetlands Converted to Cropland",
"4.B.2.d  Settlements Converted to Cropland",
"4.B.2.e  Other Land Converted to Cropland",
"4.C  Grassland",
"4.C.1  Grassland Remaining Grassland",
"4.C.2  Land Converted to Grassland",
"4.C.2.a  Forest Land Converted to Grassland",
"4.C.2.b  Cropland Converted to Grassland",
"4.C.2.c  Wetlands Converted to Grassland",
"4.C.2.d  Settlements Converted to Grassland",
"4.C.2.e  Other Land Converted to Grassland",
"4.D  Wetlands",
"4.D.1  Wetlands Remaining Wetlands",
"4.D.1.a  Peat Extraction Remaining Peat Extraction",
"4.D.1.b  Flooded Land Remaining Flooded Land",
"4.D.1.c  Other Wetlands Remaining Other Wetlands",
"4.D.2  Land Converted to Wetlands",
"4.E  Settlements",
"4.E.1  Settlements Remaining Settlements",
"4.E.2  Land Converted to Settlements",
"4.E.2.a  Forest Land Converted to Settlements",
"4.E.2.b  Cropland Converted to Settlements",
"4.E.2.c  Grassland Converted to Settlements",
"4.E.2.d  Wetlands Converted to Settlements",
"4.E.2.e  Other Land Converted to Settlements",
"4.F  Other Land",
"4.F.2  Land Converted to Other Land",
"4.F.2.a  Forest Land Converted to Other Land",
"4.F.2.b  Cropland Converted to Other Land",
"4.F.2.c  Grassland Converted  to Other Land",
"4.F.2.d  Wetlands Converted to Other Land",
"4.F.2.e  Settlements Converted to Other Land",
"4.G  Harvested Wood Products",
"4.G.1  Solid Wood",
"4.G.1.a  Sawnwood",
"4.G.1.b  Wood Panels",
"4.G.1.c  Other Solid Wood Products",
"4.G.2  Paper and Paperboard",
"4.G.3  Other",
"4.H  Other",
"5.  Waste",
"5.A  Solid Waste Disposal",
"5.A.1  Managed Waste Disposal Sites",
"5.A.1.a  Anaerobic",
"5.A.1.b  Semi-aerobic",
"5.A.2  Unmanaged Waste Disposal Sites",
"5.A.3  Uncategorized Waste Disposal Sites",
"5.B  Biological Treatment of Solid Waste",
"5.B.1  Composting",
"5.B.1.a  Municipal Solid Waste",
"5.B.1.b  Other",
"5.B.2  Anaerobic Digestion at Biogas Facilities",
"5.B.2.a  Municipal Solid Waste",
"5.B.2.b  Other",
"5.C  Incineration and Open Burning of Waste",
"5.C.1  Waste Incineration",
"5.C.1.a  Biogenic",
"5.C.1.a.i  Municipal Solid Waste",
"5.C.1.a.ii  Other",
"5.C.1.a.ii.1  Industrial Solid Wastes",
"5.C.1.a.ii.2  Hazardous Waste",
"5.C.1.a.ii.3  Clinical Waste",
"5.C.1.a.ii.4  Sewage Sludge",
"5.C.1.a.ii.5  Other",
"5.C.1.b  Non-biogenic",
"5.C.1.b.i  Municipal Solid Waste",
"5.C.1.b.ii  Other",
"5.C.1.b.ii.1  Industrial Solid Wastes",
"5.C.1.b.ii.2  Hazardous Waste",
"5.C.1.b.ii.3  Clinical Waste",
"5.C.1.b.ii.4  Sewage Sludge",
"5.C.1.b.ii.5  Fossil Liquid Waste",
"5.C.1.b.ii.6  Other",
"5.C.2  Open Burning of Waste",
"5.C.2.a  Biogenic",
"5.C.2.a.i  Municipal Solid Waste",
"5.C.2.a.ii  Other",
"5.C.2.b  Non-biogenic",
"5.C.2.b.i  Municipal Solid Waste",
"5.C.2.b.ii  Other",
"5.D  Wastewater Treatment and Discharge",
"5.D.1  Domestic Wastewater",
"5.D.2  Industrial Wastewater",
"5.D.3  Other",
"5.E  Other",
"6.  Other"]

# get categories without repeat whitespace
UNFCCC_CATEGORIES_NO_REPEAT_WHITESPACE = [re.sub(r'\s+',' ',cat) for cat in UNFCCC_CATEGORIES]

# get categories without any whitespace
UNFCCC_CATEGORIES_NO_WHITESPACE = [re.sub(r'\s+','',cat) for cat in UNFCCC_CATEGORIES]

def is_valid_unfccc_cat(value, ignore_repeat_whitespace = True, ignore_all_whitespace = True):
	"""Returns True if the value is a valid UNFCCC category

	   Parameters:
	   value (str): input string to check against categories
	   ignore_repeat_whitespace (bool): Ignore repeating whitespace characters (default True)
   	   ignore_all_whitespace (bool): Ignore all whitespace (default True)

	"""
	if ignore_all_whitespace:
		value_no_whitespace = re.sub(r'\s+','',value)
		return value_no_whitespace in UNFCCC_CATEGORIES_NO_WHITESPACE
	elif ignore_repeat_whitespace:
		value_no_repeat_whitespace = re.sub(r'\s+',' ',value)
		return value_no_repeat_whitespace in UNFCCC_CATEGORIES_NO_REPEAT_WHITESPACE
	else:
		return value in UNFCCC_CATEGORIES

